spring.application.name=InventoryManagment

# Database Configuration
spring.datasource.url=jdbc:postgresql://inventory.cfmckece6q7m.ap-northeast-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=inventory

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=your-secret-key-here-must-be-at-least-32-characters-long-for-hs256
jwt.expiration=86400000
